#!/bin/bash

javac boxshogi/Main.java
java boxshogi/Main -f ./test_cases/$1.in | diff -s  - ./test_cases/$1.out -i -w -B > /dev/null
if [ $? -eq 1 ]
then
    java boxshogi/Main -f ./test_cases/$1.in | icdiff /dev/stdin ./test_cases/$1.out --whole-file --label=Actual --label=Expected
    exit 1
fi
