#!/bin/bash

java Main -f ./"BoxShogi Test Cases"/$1.in | diff -s  - ./"BoxShogi Test Cases"/$1.out -i -w -B > /dev/null
if [ $? -eq 1 ]
then
    java Main -f ./"BoxShogi Test Cases"/$1.in | icdiff /dev/stdin ./"BoxShogi Test Cases"/$1.out --whole-file --label=Actual --label=Expected
    exit 1
fi
